"""Prepare an inverted STILL endpoint; actual movement is generated by fal video."""
from pathlib import Path
from PIL import Image
import json

ROOT = Path(__file__).resolve().parent
source = ROOT / 'images/07-finger-dance.png'
target = ROOT / 'images/07-finger-dance-inverted-end.png'
Image.open(source).rotate(180).save(target)
spec_path = ROOT / 'prompts/07-finger-dance-motion.json'
spec = json.loads(spec_path.read_text())
spec['source'] = '07-finger-dance'
spec['end_source'] = '07-finger-dance-inverted-end'
spec['prompt'] = (
    'A real articulated three-dimensional hand does a little breakdance. Locked stationary camera, '
    'single continuous shot, the exact butter-yellow five-digit hand in the supplied start frame. '
    'During the FIRST SECOND the WHOLE HAND flips smoothly head-over-heels 180 degrees as a solid '
    'three-dimensional object, with the short wrist stump moving to the TOP. It lands UPSIDE DOWN '
    'on the fingertips of its INDEX and MIDDLE fingers. These two anatomical fingers are its two '
    'dancing supports. Ring and pinky remain separately folded toward the palm, thumb stays folded '
    'at the side: exactly FIVE digits throughout. During the REMAINING TWO SECONDS the index and '
    'middle fingers take four clear alternating little dance steps. Their REAL FINGER JOINTS '
    'bend and extend independently, fingertips lift from and touch the floor in turn, weight '
    'shifts between the two fingers, palm bobs gently above them. The supporting fingers behave '
    'like the two legs of a little dancer, but NEVER create separate legs, feet, toes or shoes. '
    'Finish standing upside down on those two fingers, matching the end frame. The palm face '
    'is a fixed physical marking: the tiny brown eyes and happy smile rotate WITH the hand, '
    'ending upside down near the wrist at the TOP of the palm. Do not redraw the face upright, '
    'move the face or morph its smile. The opposite back permanently has a separate frown, '
    'visible only if the back itself is exposed. Same soft rounded butter-yellow 3D toy '
    'material, clear silhouette, ivory background. NO CAMERA MOVEMENT, cuts, zoom, extra '
    'hands, new props, audio or text. This must contain REAL finger-joint articulation and '
    'alternating finger steps, not a still picture spinning or sliding. Telegram hand-emoji '
    'motion timing: anticipatory elastic flip, quick crisp fingertip steps, soft settle.'
)
spec_path.write_text(json.dumps(spec, indent=2)+'\n')
(ROOT / 'dance-endpoint-provenance.json').write_text(json.dumps({
    'source': str(source), 'end_still': str(target),
    'operation': '180-degree local rotation of an existing genuine five-digit native pose',
    'purpose': 'End-frame conditioning only, NOT an animation or a newly generated image',
    'actual_animation_provider': 'fal Kling O3 Pro reference-to-video, after reviewed submission',
    'user_choreography': 'Hand flips over to stand on its fingers and dances on its fingers'
}, indent=2)+'\n')
print('Prepared upside-down dance end frame and corrected real-motion prompt.')